- name: checking service status
  hosts: redhatservers
  tasks:
  - name: Checking Service Status
    command: systemctl status "{{ item }}"
    with_items:
    - firewalld
    - httpd
    - vsftpd
    - sshd
    - cups
    register: result
    ignore_errors: yes
  - name: showing report
    debug:
     var: result
